# Greets users upon making their first issue.

name: Greetings
on: [pull_request]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: 'Hello! Thank you for taking the time to submit a contribution to the GenshinMap project. Your pull request will be reviewed shortly.'
